env:
  browser: true
  es6: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:import/typescript'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules: {
  "comma-dangle": ["error", "always-multiline"],
  "no-undef": "off",
  "no-unused-vars": "off",
  "no-use-before-define": "off"
}
